language: go

go:
  - 1.10.x
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
install:
  - dep ensure

  - gox -ldflags "-X main.version=$(git describe --long --tag --dirty)" -osarch="linux/amd64" -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file: "dist/linux_amd64_kubernetes-launcher"
  skip_cleanup: true
  on:
    tags: true
